I wrote fizzbuzz practice
Fuki3/ruby-practices pull request #1
Opened 2023-05-03 13:06 UTC by Fuki3

2023-05-14 05:20 UTC, summertree128 requested changes

2023-05-14 05:20 UTC, summertree128 commented on 01.fizzbuzz/fizzbuzz.rb
> +  end
このように`if`を複数並べると、毎回のループで全ての条件を上から順番にチェックすることになります。もしなにかの間違いで複数の条件を満たすようなことがあれば、一つの数字に対して複数回出力がされてしまうことになります。

実際には一つの数字に対しては一度だけ出力してほしいので、上から順番に条件をチェックして、一度でも条件に当てはまったらそこで条件判定を終えてほしいところです。

`elsif`や`else`を使えばそういう構造にできるので、そのようにリファクタリングしてみてください。

2023-05-14 14:00 UTC, Fuki3 commented on 01.fizzbuzz/fizzbuzz.rb
> +  end
理解しました、ご教示いただきありがとうございます。
修正いたしました、ご確認おねがいいたします。

2023-05-17 00:43 UTC, summertree128 requested changes

2023-05-17 00:43 UTC, summertree128 commented on 01.fizzbuzz/fizzbuzz.rb
> +  elsif fizzbuzz % 3 == 0 && fizzbuzz % 5 != 0
前半の条件を満たす場合、自動的に後半の条件も満たすことになりますね。（すでに15で割り切れないことは分かっているため）
なので、後半の条件は必要ありません。消しちゃいましょう。
もう一つのelsifについても同様です。

2023-05-17 00:43 UTC, summertree128 commented on 01.fizzbuzz/fizzbuzz.rb
> +  else fizzbuzz % 3 != 0 && fizzbuzz % 5 != 0
else に条件式は不要です。リファレンスや書籍を見直してみてください。〜

2023-05-17 05:09 UTC, Fuki3 commented on 01.fizzbuzz/fizzbuzz.rb
> +  else fizzbuzz % 3 != 0 && fizzbuzz % 5 != 0
そうでした、申し訳ありません、
修正したものを再度pushいたしました。ご確認おねがいいたします。

2023-05-19 06:01 UTC, summertree128 approved these changes
レビューOKです！お疲れ様でした！

このままマージしてもらって構わないのですが、せっかくなのでいくつかアドバイス的なものをここにコメントしておきます。

- `fizzbuzz`という変数名は若干変数の役割と乖離しているというか、今`fizzbuzz`変数に入っているのはただの数字なので、`number`とか`num`みたいな変数名のほうが適切かなと思いました。Fizzbuzzをやってるのはこのスクリプト全体なので、Fizzbuzzという名前を持つべきなのはファイルそのものですね。（なのでこのファイル名は適切です）
- Rubyには繰り返しを実現する制御構文がいくつかありますが、今回のようなケースでは`while`はあまり使われません。理由としては、繰り返しを終了するための条件を自分で管理する必要があり、ちょっとしたミスですぐ無限ループを発生させてしまったり、逆に必要な分繰り返しできずに終わってしまったりする可能性があり安全でないからです。今回は1から20までという決まった回数繰り返すので、終了条件を自分で管理する必要のない別の方法の方が安全です。公式リファレンスや他の方の提出物等を見て、より安全な書き方がどのようなものか調べてみてください〜

2023-05-20 13:18 UTC, Fuki3 commented
ありがとうございます🙇🏻‍♀️
いただいたアドバイスと他の方の提出物を参考に、復習します。

2023-05-20 13:29 UTC, merged